### ISSUE TITLE
Remove duplicate favicon

### ISSUE THREAD

**Issue by benedfit** [mattybeard/Destiny-Daily-2#13]
There is an old favicon in the root of the site. Move the one from `/assets/img/meta` to the root and then update the path in `<head>` of Layout

**Comment by mattybeard** [comment]
Favicon removed from route. @benedfit can we not just leave as is now?

**Comment by benedfit** [comment]
It's actually better for us to move it, lots of old browsers auto check for /favicon.ico, so it prevents lots of 404s just to have it in the root. I need to update the meta icons, as I missed a few, anyway, so I'll make the change when I do that

**Comment by mattybeard** [comment]
Moved in live code, just need to move in template code for next update.
