### ISSUE TITLE
Setup domain redirects

### ISSUE THREAD

**Issue by benedfit** [mattybeard/Destiny-Daily-2#15]
As discussed last night; point the naked apex domain at the site too, and then decided which domain (http://destiny-daily.com, or http://www.destiny-daily.com) should be the primary domain, then setup a redirect from the other to it

**Comment by mattybeard** [comment]
This should be done, just need to check after DNS is resolved.

**Comment by benedfit** [comment]
DNS is correct, but the redirect isn't happening yet

**Comment by mattybeard** [comment]
Done.
