### ISSUE TITLE
Setup up 301 redirects

### ISSUE THREAD

**Issue by benedfit** [mattybeard/Destiny-Daily-2#16]
Here are my suggestions for 301 redirects for existing pages in Google (there is some work needed to give each section a jump link before all of this is possible though):

- [x] /PrisonOfElders => /weekly#challenge-of-elders
- [x] /Heroic => /
- [x] /Xur => /vendors#xur
- [x] /Clan => /
- [x] /Fragment => /
- [x] /Weekly/Weekly => /weekly
- [x] /Weekly/Nightfall => /nightfall
- [x] /Clan/GetRekt => /
- [x] /Nightfall/Sorry => /nightfall
- [x] /Bounty/Previous* => /
- [x] /Twitch => /
- [x] /Bounty/Yesterday => /
- [x] /Daily/Previous* => /daily
- [x] /Bounty/Edit => /
- [x] /History => /
- [x] /Daily/LoadLatest => /daily
- [x] /Bounty/LoadLatest => /

**Comment by mattybeard** [comment]
Done!

**Comment by mattybeard** [comment]
Reopened, anchor points still needed...

**Comment by mattybeard** [comment]
Closed, anchor points as seperate issue.

**Comment by benedfit** [comment]
I've added a few more that have appeared, and ticked off all those that are working

**Comment by mattybeard** [comment]
Fixed all missing ones. Had an errant slash in some of the older ones too.

**Comment by benedfit** [comment]
👍

**Comment by benedfit** [comment]
Found a couple more after digging around in Google webmaster tools

**Comment by mattybeard** [comment]
Still had it open so done!

**Comment by benedfit** [comment]
Found another one

**Comment by benedfit** [comment]
Done
