### ISSUE TITLE
Setup 404 page

### ISSUE THREAD

**Issue by benedfit** [mattybeard/Destiny-Daily-2#17]
I don't know if this is still an issue, but sometimes the 404 handler in .NET sites doesn't return the correct 404 HTTP header, instead performing a 302 redirect to an error page

**Comment by benedfit** [comment]
Unfortunately it current returned a 302 e.g. http://tools.seobook.com/server-header-checker/?page=single&url=http%3A%2F%2Fwww.destiny-daily.com%2Fbanana&useragent=1&typeProtocol=11

**Comment by benedfit** [comment]
Additional IIS configuration may be needed too as some static files are returning a different 404 page e.g. http://www.destiny-daily.com/blah.txt

**Comment by mattybeard** [comment]
@benedfit It's difficult - it's hosted in Azure so you don't get the IIS options like you would normally so I'm a little limited. Will need to find alternate ways to handle it in Azure.

**Comment by benedfit** [comment]
Could we adjust the handlers in web.config so everything goes through the MVC routing handler? It's been a while since I did this stuff and I've forgotten 😄
