### ISSUE TITLE
Setup Google webmaster tools

### ISSUE THREAD

**Issue by benedfit** [mattybeard/Destiny-Daily-2#30]
- [x] Register site with Google webmaster tools in not already done some (use Google Analytics method of validation as it's set up)
- [x] Create XML sitemap
- [x] Create robots.txt with link to XML sitemap

**Comment by benedfit** [comment]
#34 disables them for the time being

**Comment by benedfit** [comment]
@mattybeard both robots.txt and sitemap.xml were merged in my last PR, but unfortunately neither a reachable and are 404ing in production, can you take a look at the Azure settings and see if anything else needs doing?

**Comment by mattybeard** [comment]
Done for JSON and TXT

**Comment by benedfit** [comment]
Reopening while waiting for latest robots.txt to be deployed, and for sitemap.xml to be reachable

**Comment by mattybeard** [comment]
All done and you can stop complaining about your web standards now ;)

Sorry I didn't get around to it last night.
